// basic
import '/imports/startup/client';
import '/imports/i18n/client';
import '/imports/autoform';
import '/imports/layout';
import '/imports/files/client';
import '/imports/website/client';
import '/imports/profile/client';
import '/imports/inbox';
import '/imports/email/client';
import '/imports/chat/client';
// modules
import '/imports/channel/client';
import '/imports/roster/client';
import '/imports/charts/client';
import '/imports/search/client';
import '/imports/shared/client';
import '/imports/cordova/client';
