// basic
import '/imports/i18n/client';
import '/imports/startup/client';
import '/imports/autoform';
import '/imports/layout';
import '/imports/files/client';
import '/imports/website/client';
import '/imports/profile/client';
import '/imports/inbox/client';
import '/imports/email/client';
import '/imports/chat/client';
import '/imports/group/client';
import '/imports/star/client';
// modules
import '/imports/channel/client';
import '/imports/roster/client';
import '/imports/charts/client';
import '/imports/search/client';
import '/imports/shared/client';
import '/imports/live-chat/client';
import '/imports/mailgun/client';
import '/imports/cordova/client';
