#!/bin/bash

curl -SLf "https://github.com/wanglian/workbase-server/releases/download/v0.0.1/workbase.tar.gz" -o workbase.tar.gz

tar xf workbase.tar.gz --strip 1

cd programs/server

export NODE_ENV=production
npm i
